package com.astonm.springbootdemo.pojo;

import java.io.Serializable;
import java.util.Date;

public class User implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user1.id
     *
     * @mbggenerated Sat Jul 03 23:20:16 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user1.name
     *
     * @mbggenerated Sat Jul 03 23:20:16 CST 2021
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user1.age
     *
     * @mbggenerated Sat Jul 03 23:20:16 CST 2021
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user1.sex
     *
     * @mbggenerated Sat Jul 03 23:20:16 CST 2021
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user1.phoneNumber
     *
     * @mbggenerated Sat Jul 03 23:20:16 CST 2021
     */
    private String phonenumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user1.addr
     *
     * @mbggenerated Sat Jul 03 23:20:16 CST 2021
     */
    private String addr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user1.comment
     *
     * @mbggenerated Sat Jul 03 23:20:16 CST 2021
     */
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user1.lastLoginTime
     *
     * @mbggenerated Sat Jul 03 23:20:16 CST 2021
     */
    private Date lastlogintime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user1.signUpTime
     *
     * @mbggenerated Sat Jul 03 23:20:16 CST 2021
     */
    private Date signuptime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user1
     *
     * @mbggenerated Sat Jul 03 23:20:16 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user1.id
     *
     * @return the value of user1.id
     *
     * @mbggenerated Sat Jul 03 23:20:16 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user1.id
     *
     * @param id the value for user1.id
     *
     * @mbggenerated Sat Jul 03 23:20:16 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user1.name
     *
     * @return the value of user1.name
     *
     * @mbggenerated Sat Jul 03 23:20:16 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user1.name
     *
     * @param name the value for user1.name
     *
     * @mbggenerated Sat Jul 03 23:20:16 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user1.age
     *
     * @return the value of user1.age
     *
     * @mbggenerated Sat Jul 03 23:20:16 CST 2021
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user1.age
     *
     * @param age the value for user1.age
     *
     * @mbggenerated Sat Jul 03 23:20:16 CST 2021
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user1.sex
     *
     * @return the value of user1.sex
     *
     * @mbggenerated Sat Jul 03 23:20:16 CST 2021
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user1.sex
     *
     * @param sex the value for user1.sex
     *
     * @mbggenerated Sat Jul 03 23:20:16 CST 2021
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user1.phoneNumber
     *
     * @return the value of user1.phoneNumber
     *
     * @mbggenerated Sat Jul 03 23:20:16 CST 2021
     */
    public String getPhonenumber() {
        return phonenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user1.phoneNumber
     *
     * @param phonenumber the value for user1.phoneNumber
     *
     * @mbggenerated Sat Jul 03 23:20:16 CST 2021
     */
    public void setPhonenumber(String phonenumber) {
        this.phonenumber = phonenumber == null ? null : phonenumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user1.addr
     *
     * @return the value of user1.addr
     *
     * @mbggenerated Sat Jul 03 23:20:16 CST 2021
     */
    public String getAddr() {
        return addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user1.addr
     *
     * @param addr the value for user1.addr
     *
     * @mbggenerated Sat Jul 03 23:20:16 CST 2021
     */
    public void setAddr(String addr) {
        this.addr = addr == null ? null : addr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user1.comment
     *
     * @return the value of user1.comment
     *
     * @mbggenerated Sat Jul 03 23:20:16 CST 2021
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user1.comment
     *
     * @param comment the value for user1.comment
     *
     * @mbggenerated Sat Jul 03 23:20:16 CST 2021
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user1.lastLoginTime
     *
     * @return the value of user1.lastLoginTime
     *
     * @mbggenerated Sat Jul 03 23:20:16 CST 2021
     */
    public Date getLastlogintime() {
        return lastlogintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user1.lastLoginTime
     *
     * @param lastlogintime the value for user1.lastLoginTime
     *
     * @mbggenerated Sat Jul 03 23:20:16 CST 2021
     */
    public void setLastlogintime(Date lastlogintime) {
        this.lastlogintime = lastlogintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user1.signUpTime
     *
     * @return the value of user1.signUpTime
     *
     * @mbggenerated Sat Jul 03 23:20:16 CST 2021
     */
    public Date getSignuptime() {
        return signuptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user1.signUpTime
     *
     * @param signuptime the value for user1.signUpTime
     *
     * @mbggenerated Sat Jul 03 23:20:16 CST 2021
     */
    public void setSignuptime(Date signuptime) {
        this.signuptime = signuptime;
    }
}